site:
  theme: Editorial
  about:
    siteName: Stalla
    siteDescription: This is a short description of this project.

theme:
  extraCss:
    - 'assets/css/custom.scss'
  menu:
    - type: 'wiki'
      title: 'Manual'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
    - type: 'page'
      itemId: 'Changelog'

Editorial:
  primaryColor: '#0098f1'
  legacySearch: false
  social:
    github: 'mpgirro/stalla'
  metaComponents:
    - type: 'orchidSearch'

kotlindoc:
  sourceDirs:
    - './../../main/kotlin'
  showRunnerLogs: false
  homePageOnly: false
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        itemTitleType: 'signature'
        includeItems: true
  classesPages:
    layoutConfig:
      pageContentsMenu:
        - type: 'sourcedocPageLinks'
          includeItems: true
          itemTitleType: "SIGNATURE"
  packagesPages:
    layoutConfig:
      pageContentsMenu:
        - type: 'sourcedocPageLinks'
          includeItems: true

wiki:
  sections:
    manual:
      adapter:
        type: "github"
        repo: "mpgirro/stalla"
